# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.WidgetFor3d = QtWidgets.QWidget(self.centralwidget)
        self.WidgetFor3d.setGeometry(QtCore.QRect(10, 10, 431, 541))
        self.WidgetFor3d.setObjectName("WidgetFor3d")
        self.graphicsViewForRotatingName = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsViewForRotatingName.setGeometry(QtCore.QRect(790, 450, 171, 101))
        self.graphicsViewForRotatingName.setObjectName("graphicsViewForRotatingName")
        self.LabelForText = QtWidgets.QLabel(self.centralwidget)
        self.LabelForText.setGeometry(QtCore.QRect(450, 10, 511, 431))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading Semibold")
        font.setPointSize(16)
        self.LabelForText.setFont(font)
        self.LabelForText.setTextFormat(QtCore.Qt.AutoText)
        self.LabelForText.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelForText.setObjectName("LabelForText")
        self.ButtonForTextChange = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonForTextChange.setGeometry(QtCore.QRect(640, 470, 141, 81))
        self.ButtonForTextChange.setObjectName("ButtonForTextChange")
        self.ButtonToStopMusic = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonToStopMusic.setGeometry(QtCore.QRect(460, 470, 151, 81))
        self.ButtonToStopMusic.setObjectName("ButtonToStopMusic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LabelForText.setText(_translate("MainWindow", "TextLabel"))
        self.ButtonForTextChange.setText(_translate("MainWindow", "PushButton"))
        self.ButtonToStopMusic.setText(_translate("MainWindow", "PushButton"))
